### ISSUE TITLE
Please clarify example

### ISSUE THREAD

**Issue by Antonboom** [charithe/durationcheck#11]
Hello!

```
A caller would reasonably expect waitFor(5 * time.Seconds) to wait for ~5 seconds 
but they would actually end up waiting for ~1,388,889 hours.
```

Where did these numbers come from?
The function will sleep 5 seconds as expected:
https://goplay.tools/snippet/izCeDb5NL9W

Are you talking about some tricky runtime feature?
Or do you mean that I can pass not `5`, but a larger number? Why did it turn out `1,388,889 hours` exactly?
Or what are we talking about?

Thanks!

**Comment by charithe** [comment]
You are passing `5` to the function in your snippet -- which is the correct way to invoke it. However, if you pass `5 * time.Second` then the compiler won't complain but you'll end up sleeping for ~1,388,889 hours. See https://play.golang.org/p/HzxB_G5LrG9

**Comment by Antonboom** [comment]
I got it.

Maybe update readme like other linters with "correct vs incorrect"?
Although my inattention is to blame :(

Thank u for useful tool!
