### ISSUE TITLE
False positive caused by brackets

### ISSUE THREAD

**Issue by sb10** [charithe/durationcheck#14]
`time.Duration(attempts) * time.Millisecond` is fine, but
`time.Duration((attempts)) * time.Millisecond` causes a false positive.

(The real scenario was doing some maths inside the time.Duration(): `time.Duration((attempts-1)*2)*time.Millisecond)`.)

**Comment by Gentoli** [comment]
Seems when the bracketed case have no space it will still fail:
`time.Duration((c + 1) * 200) * time.Millisecond` will pass,
`time.Duration((c+1)*200) * time.Millisecond` fails

**Comment by charithe** [comment]
Hmm...I can't reproduce that case. First of all, I had to disable `gofmt` to even type in the expression without spaces. When I eventually did, the linter was still happy. I can't see why it wouldn't be because it's using the AST produced by the Go parser and spaces are irrelevant to the parser.

**Comment by Gentoli** [comment]
I am using https://github.com/golangci/golangci-lint, maybe something is wrong on their side..

**Comment by charithe** [comment]
I still can't reproduce with either golangcl-lint (1.40.2) or the standalone linter. Weird! 🤷🏽

**Comment by Gentoli** [comment]
I just realized golangcl-lint (1.40.1) is still on 0.6 🤦. Installing the latest resolved the issue. Thank you for checking 🙏.
