### ISSUE TITLE
Why is the code in Readme wrong?

### ISSUE THREAD

**Issue by frederikhors** [charithe/durationcheck#18]
Can I ask you why the code in Readme is wrong?

```go
func waitFor(someDuration time.Duration) {
    timeToWait := someDuration * time.Second
    time.Sleep(timeToWait)
}
```

**Comment by frederikhors** [comment]
I just found https://github.com/golang/go/issues/20757.

**Comment by charithe** [comment]
It's not syntactically wrong but it's semantically wrong.

Perhaps this will explain it better: https://github.com/charithe/durationcheck/issues/11#issuecomment-782611051

**Comment by frederikhors** [comment]
Can you please explain it better in Readme?
