### ISSUE TITLE
integration with golangci-lint

### ISSUE THREAD

**Issue by SVilgelm** [charithe/durationcheck#6]
Hi,
I found you linter is very useful, but it would be great if you can integrate it with [golangci-lint](https://github.com/golangci/golangci-lint)
I did an attempt, but looks like it requires some changes in your code

**Comment by charithe** [comment]
Where did you stumble with the integration? Do you know what needs to change?

**Comment by ldez** [comment]
Hello,

I created an integration with golangci-lint and I don't see any issue with this linter.

https://github.com/golangci/golangci-lint/pull/1734

@SVilgelm am I missing something?

**Comment by charithe** [comment]
Nice work @ldez. Thank you. 

Since @ldez has kindly taken on the integration work and raised a PR against golangci-lint, I will close this issue.
